---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

## Assignment 4 - Understanding and Predicting Property Maintenance Fines

This assignment is based on a data challenge from the Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)). 

The Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)) and the Michigan Student Symposium for Interdisciplinary Statistical Sciences ([MSSISS](https://sites.lsa.umich.edu/mssiss/)) have partnered with the City of Detroit to help solve one of the most pressing problems facing Detroit - blight. [Blight violations](http://www.detroitmi.gov/How-Do-I/Report/Blight-Complaint-FAQs) are issued by the city to individuals who allow their properties to remain in a deteriorated condition. Every year, the city of Detroit issues millions of dollars in fines to residents and every year, many of these fines remain unpaid. Enforcing unpaid blight fines is a costly and tedious process, so the city wants to know: how can we increase blight ticket compliance?

The first step in answering this question is understanding when and why a resident might fail to comply with a blight ticket. This is where predictive modeling comes in. For this assignment, your task is to predict whether a given blight ticket will be paid on time.

All data for this assignment has been provided to us through the [Detroit Open Data Portal](https://data.detroitmi.gov/). **Only the data already included in your Coursera directory can be used for training the model for this assignment.** Nonetheless, we encourage you to look into data from other Detroit datasets to help inform feature creation and model selection. We recommend taking a look at the following related datasets:

* [Building Permits](https://data.detroitmi.gov/Property-Parcels/Building-Permits/xw2a-a7tf)
* [Trades Permits](https://data.detroitmi.gov/Property-Parcels/Trades-Permits/635b-dsgv)
* [Improve Detroit: Submitted Issues](https://data.detroitmi.gov/Government/Improve-Detroit-Submitted-Issues/fwz3-w3yn)
* [DPD: Citizen Complaints](https://data.detroitmi.gov/Public-Safety/DPD-Citizen-Complaints-2016/kahe-efs3)
* [Parcel Map](https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwf)

___

We provide you with two data files for use in training and validating your models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

<br>

**File descriptions** (Use only this data for training your model!)

    readonly/train.csv - the training set (all tickets issued 2004-2011)
    readonly/test.csv - the test set (all tickets issued 2012-2016)
    readonly/addresses.csv & readonly/latlons.csv - mapping from ticket id to addresses, and from addresses to lat/lon coordinates. 
     Note: misspelled addresses may be incorrectly geolocated.

<br>

**Data fields**

train.csv & test.csv

    ticket_id - unique identifier for tickets
    agency_name - Agency that issued the ticket
    inspector_name - Name of inspector that issued the ticket
    violator_name - Name of the person/organization that the ticket was issued to
    violation_street_number, violation_street_name, violation_zip_code - Address where the violation occurred
    mailing_address_str_number, mailing_address_str_name, city, state, zip_code, non_us_str_code, country - Mailing address of the violator
    ticket_issued_date - Date and time the ticket was issued
    hearing_date - Date and time the violator's hearing was scheduled
    violation_code, violation_description - Type of violation
    disposition - Judgment and judgement type
    fine_amount - Violation fine amount, excluding fees
    admin_fee - $20 fee assigned to responsible judgments
state_fee - $10 fee assigned to responsible judgments
    late_fee - 10% fee assigned to responsible judgments
    discount_amount - discount applied, if any
    clean_up_cost - DPW clean-up or graffiti removal cost
    judgment_amount - Sum of all fines and fees
    grafitti_status - Flag for graffiti violations
    
train.csv only

    payment_amount - Amount paid, if any
    payment_date - Date payment was made, if it was received
    payment_status - Current payment status as of Feb 1 2017
    balance_due - Fines and fees still owed
    collection_status - Flag for payments in collections
    compliance [target variable for prediction] 
     Null = Not responsible
     0 = Responsible, non-compliant
     1 = Responsible, compliant
    compliance_detail - More information on why each ticket was marked compliant or non-compliant


___

## Evaluation

Your predictions will be given as the probability that the corresponding blight ticket will be paid on time.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC). 

Your grade will be based on the AUC score computed for your classifier. A model which with an AUROC of 0.7 passes this assignment, over 0.75 will recieve full points.
___

For this assignment, create a function that trains a model to predict blight ticket compliance in Detroit using `readonly/train.csv`. Using this model, return a series of length 61001 with the data being the probability that each corresponding ticket from `readonly/test.csv` will be paid, and the index being the ticket_id.

Example:

    ticket_id
       284932    0.531842
       285362    0.401958
       285361    0.105928
       285338    0.018572
                 ...
       376499    0.208567
       376500    0.818759
       369851    0.018528
       Name: compliance, dtype: float32
       
### Hints

* Make sure your code is working before submitting it to the autograder.

* Print out your result to see whether there is anything weird (e.g., all probabilities are the same).

* Generally the total runtime should be less than 10 mins. You should NOT use Neural Network related classifiers (e.g., MLPClassifier) in this question. 

* Try to avoid global variables. If you have other functions besides blight_model, you should move those functions inside the scope of blight_model.

* Refer to the pinned threads in Week 4's discussion forum when there is something you could not figure it out.

In [3]:
import pandas as pd

train_data = pd.read_csv('data/train.csv', encoding='cp1252')
train_data.head()

C:\Users\luisa\AppData\Local\Temp\ipykernel_9712\580077585.py:3: DtypeWarning: Columns (11,12,31) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv('data/train.csv', encoding='cp1252')

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
0,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
1,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
2,22062,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","SANDERS, DERRON",1449.0,LONGFELLOW,NaN,23658.0,P.O. BOX,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
3,22084,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","MOROSI, MIKE",1441.0,LONGFELLOW,NaN,5.0,ST. CLAIR,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
4,22093,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","NATHANIEL, NEAL",2449.0,CHURCHILL,NaN,7449.0,CHURCHILL,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250306 entries, 0 to 250305
Data columns (total 34 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   ticket_id                   250306 non-null  int64
 1   agency_name                 250306 non-null  object
 2   inspector_name              250306 non-null  object
 3   violator_name               250272 non-null  object
 4   violation_street_number     250306 non-null  float64
 5   violation_street_name       250306 non-null  object
 6   violation_zip_code          0 non-null       float64
 7   mailing_address_str_number  246704 non-null  float64
 8   mailing_address_str_name    250302 non-null  object
 9   city                        250306 non-null  object
 10  state                       250213 non-null  object
 11  zip_code                    250305 non-null  object
 12  non_us_str_code             3 non-null       object
 13  country                     250306 non-null  object
 14  ticket_issued_date          250306 non-null  object
 15  hearing_date                237815 non-null  object
 16  violation_code              250306 non-null  object
 17  violation_description       250306 non-null  object
 18  disposition                 250306 non-null  object
 19  fine_amount                 250305 non-null  float64
 20  admin_fee                   250306 non-null  float64
 21  state_fee                   250306 non-null  float64
 22  late_fee                    250306 non-null  float64
 23  discount_amount             250306 non-null  float64
 24  clean_up_cost               250306 non-null  float64
 25  judgment_amount             250306 non-null  float64
 26  payment_amount              250306 non-null  float64
 27  balance_due                 250306 non-null  float64
 28  payment_date                41113 non-null   object
 29  payment_status              250306 non-null  object
 30  collection_status           36897 non-null   object
 31  grafitti_status             1 non-null       object
 32  compliance_detail           250306 non-null  object
 33  compliance                  159880 non-null  float64
dtypes: float64(13), int64(1), object(20)
memory usage: 64.9+ MB

In [5]:
test_data = pd.read_csv('data/test.csv')
test_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,violation_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,grafitti_status
0,284932,Department of Public Works,"Granberry, Aisha B","FLUELLEN, JOHN A",10041.0,ROSEBERRY,NaN,141,ROSEBERRY,DETROIT,...,Failure to secure City or Private solid waste ...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
1,285362,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,1000.0,20.0,10.0,100.0,0.0,0.0,1130.0,NaN
2,285361,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Improper placement of Courville container betw...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN
3,285338,Department of Public Works,"Talbert, Reginald","HARABEDIEN, POPKIN",1835.0,CENTRAL,NaN,2246,NELSON,WOODHAVEN,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
4,285346,Department of Public Works,"Talbert, Reginald","CORBELL, STANLEY",1700.0,CENTRAL,NaN,3435,MUNGER,LIVONIA,...,Violation of time limit for approved container...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN

In [6]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61001 entries, 0 to 61000
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ticket_id                   61001 non-null  int64
 1   agency_name                 61001 non-null  object
 2   inspector_name              61001 non-null  object
 3   violator_name               60973 non-null  object
 4   violation_street_number     61001 non-null  float64
 5   violation_street_name       61001 non-null  object
 6   violation_zip_code          24024 non-null  object
 7   mailing_address_str_number  59987 non-null  object
 8   mailing_address_str_name    60998 non-null  object
 9   city                        61000 non-null  object
 10  state                       60670 non-null  object
 11  zip_code                    60998 non-null  object
 12  non_us_str_code             0 non-null      float64
 13  country                     61001 non-null  object
 14  ticket_issued_date          61001 non-null  object
 15  hearing_date                58804 non-null  object
 16  violation_code              61001 non-null  object
 17  violation_description       61001 non-null  object
 18  disposition                 61001 non-null  object
 19  fine_amount                 61001 non-null  float64
 20  admin_fee                   61001 non-null  float64
 21  state_fee                   61001 non-null  float64
 22  late_fee                    61001 non-null  float64
 23  discount_amount             61001 non-null  float64
 24  clean_up_cost               61001 non-null  float64
 25  judgment_amount             61001 non-null  float64
 26  grafitti_status             2221 non-null   object
dtypes: float64(9), int64(1), object(17)
memory usage: 12.6+ MB

In [7]:
address_data = pd.read_csv('data/addresses.csv')
address_data.head()

   ticket_id                      address
0      22056       2900 tyler, Detroit MI
1      27586     4311 central, Detroit MI
2      22062  1449 longfellow, Detroit MI
3      22084  1441 longfellow, Detroit MI
4      22093   2449 churchill, Detroit MI

In [8]:
address_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311307 entries, 0 to 311306
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ticket_id  311307 non-null  int64
 1   address    311307 non-null  object
dtypes: int64(1), object(1)
memory usage: 4.8+ MB

In [9]:
latlon_data = pd.read_csv('data/latlons.csv')
latlon_data.head()

                                  address        lat        lon
0  4300 rosa parks blvd, Detroit MI 48208  42.346169 -83.079962
1                14512 sussex, Detroit MI  42.394657 -83.194265
2                3456 garland, Detroit MI  42.373779 -82.986228
3                5787 wayburn, Detroit MI  42.403342 -82.957805
4              5766 haverhill, Detroit MI  42.407255 -82.946295

In [10]:
latlon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121769 entries, 0 to 121768
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   address  121769 non-null  object
 1   lat      121762 non-null  float64
 2   lon      121762 non-null  float64
dtypes: float64(2), object(1)
memory usage: 2.8+ MB

In [13]:
import pandas as pd
import numpy as np

def blight_model():
    # Your code here
    # import the necessary packages
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.model_selection import train_test_split, GridSearchCV
    from sklearn.metrics import roc_auc_score
    from sklearn.preprocessing import LabelEncoder
    
    # Load data
    train_data = pd.read_csv('data/train.csv', encoding='cp1252')
    test_data = pd.read_csv('data/test.csv')
    address_data = pd.read_csv('data/addresses.csv')
    latlon_data = pd.read_csv('data/latlons.csv')
    
    # Merge lat and lon
    address_latlon = address_data.merge(latlon_data, on='address')
    train_data = train_data.merge(address_latlon, on='ticket_id')
    test_data = test_data.merge(address_latlon, on='ticket_id')
    
    # Drop compliance with NaN & Not in USA
    train_data = train_data[np.isfinite(train_data['compliance'])] # Drop NaN
    train_data = train_data[train_data['country'] == "USA"]
    test_data = test_data[test_data['country'] == "USA"]
    test_data['mailing_address_str_number'] = test_data['mailing_address_str_number'].replace(to_replace=r'[^0-9]', value=np.nan, regex=True) # Replace string values with NaN
    test_data['mailing_address_str_number'] = pd.to_numeric(test_data['mailing_address_str_number'])
    
    # Drop columns from train_data
    drop_list_X = [ 'ticket_id', 'inspector_name', 'violation_street_name', 'violation_zip_code', 'violator_name',
                    'mailing_address_str_name', 'city', 'state', 'zip_code', 'non_us_str_code', 'country',
                    'violation_description', 'clean_up_cost', 'ticket_issued_date', 'hearing_date', 'address', 'grafitti_status']
    drop_list_y = list(train_data.columns[np.where(train_data.columns == 'payment_amount')[0][0]:np.where(train_data.columns == 'compliance')[0][0]])
    train_data = train_data.drop(drop_list_X+drop_list_y, axis=1).reset_index(drop=True)
    test_data_original = test_data
    test_data = test_data.drop(drop_list_X, axis=1).reset_index(drop=True)
    
    # Encode columns
    encode_column = ['agency_name', 'disposition', 'violation_code']
    lst_train = []
    lst_test = []
    for idx, column in enumerate(encode_column):
        encoder = LabelEncoder()
        encoder.fit(pd.concat([train_data[column], test_data[column]]))
        encoded = encoder.transform(train_data[column])
        lst_train.append(encoded)
        encoded = encoder.transform(test_data[column])
        lst_test.append(encoded)
    train_dict = dict(zip(encode_column, lst_train))
    test_dict = dict(zip(encode_column, lst_test))
    for i in train_dict:
        train_data[i] = train_dict[i]
    for i in test_dict:
        test_data[i] = test_dict[i]
        
    # Define X, y & X_evaluation_test, and fill NaN
    X, y = train_data.drop(['compliance'], axis=1), train_data['compliance']
    X_evaluation_test = test_data
    for column in ['mailing_address_str_number', 'lat', 'lon']:
        X[column] = X[column].fillna(X[column].mean())
        X_evaluation_test[column] = X_evaluation_test[column].fillna(X_evaluation_test[column].mean())
        
    # Create CV to find best parameters
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    rf_clf = RandomForestRegressor()
    grid_values = {'n_estimators': [50, 75, 100], 'max_depth': [6, 9, 12]}
    grid_clf_auc = GridSearchCV(rf_clf, param_grid=grid_values, scoring='roc_auc')
    grid_clf_auc.fit(X_train, y_train)
    
    print('Grid best parameter: ', grid_clf_auc.best_params_)
    print('Grid best score: ', grid_clf_auc.best_score_)
    print("*"*100)

    # Predict X_evaluation_test
    y_evaluation_pred = grid_clf_auc.best_estimator_.predict(X_evaluation_test)

    return pd.Series(y_evaluation_pred, test_data_original['ticket_id'], name="compliance")

In [14]:
blight_model()

C:\Users\luisa\AppData\Local\Temp\ipykernel_9712\2468999592.py:13: DtypeWarning: Columns (11,12,31) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv('data/train.csv', encoding='cp1252')

Grid best parameter:  {'max_depth': 12, 'n_estimators': 75}
Grid best score:  0.8168954015214529
****************************************************************************************************

ticket_id
284932    0.089250
285362    0.013373
285361    0.048547
285338    0.052646
285346    0.073918
            ...
376496    0.014136
376497    0.014136
376499    0.064472
376500    0.065792
369851    0.913101
Name: compliance, Length: 61001, dtype: float64